parser: babel-eslint
env:
  browser: true
  node: true
  es6: true
  jest: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'prettier'
  - 'prettier/react'
parserOptions:
  ecmaFeatures:
    jsx: true
  sourceType: module
plugins:
  - react
  - prettier
rules:
  react/prop-types: 1
