name: Test
on: [push,pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: 10.x
      - name: Install
        run: yarn install
      - name: Test
        run: yarn run test     
      - name: Build
        run: yarn run build
